AI-bench work-around issue with missing command on Hibiki board
Summary:
AIBench execution on hibiki (kyoto board) failed after first execution. Execution completes, I am able to see execution metrics. However, the logic in `getBatteryState` failed.

Hibiki board doesn't have all status required by the `getBatteryState` (https://fburl.com/code/muabm7ti) function. In particular, `/sys/class/power_supply/battery/input_suspend` is absent.

However, the underlying implementation in `util.getBatteryProp` is not able to capture the file missing case, still advance to this line which cause system to throw:

```
Traceback (most recent call last):
  File "/Users/yipjustin/fbsource/buck-out/v2/gen/fbcode/9bfda53e809ed257/aibench/__run_bench_macos__/run_bench_macos#link-tree/platforms/battery_state.py", line 41, in getBatteryState
    state["disconnected"] = util.getBatteryProp("input_suspend") == "1"
  File "/Users/yipjustin/fbsource/buck-out/v2/gen/fbcode/9bfda53e809ed257/aibench/__run_bench_macos__/run_bench_macos#link-tree/platforms/android/adb.py", line 145, in getBatteryProp
    return self.shell(
IndexError: list index out of range
```

This diff is a **mitigation** by containing the exception. We introduce default values in the `state` variable, and also set the "supported" flag to false upon error.

Reviewed By: Junah-Park

Differential Revision: D43266216

fbshipit-source-id: 8ab4985552b9867700bf5df7ee4e9c4d33005071