fix aibench failed to get the right mapping info
Summary:
Skip one row INFO ------isFirst true------
 Exception: list index out of range

because of log print have race conditions:
```
PyTorchObserver {"metric":"nit_runner_memory","type":"Memory utilization","unit":"bytes","value":"289546240"}
PyTorchObserver INFO ------isFirst true------
{"metric":"nit_runner_memory peak","type":"Memory utilization","unit":"bytes","value":"289546240"}
```
https://www.internalfb.com/intern/aibench/details/898172828844988

Reviewed By: vmpuri, nausicaasnow

Differential Revision: D48455015

fbshipit-source-id: fecae1188686fb7095468d944c2c04a37bc1880a